// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flrnqqryxnanygojbhvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscm5xcXJ5eG5hbnlnb2piaHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDc0MDYsImV4cCI6MjA2MTUyMzQwNn0.vhXiY2jmz50-L9gbF69ON59kmjd65wgWBV691P-2N5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);